### PR TITLE
Migrate CBOR representation to NOTE

### PR DESCRIPTION
**Pull request by msporny**
This PR implements the first part of the following DID WG resolution:

Resolution #1 on 2021-05-04: remove CBOR from the DID Core Specification, publish it as a WG Note, and add CBOR to the DID Spec Registries with a reference to the WG Note

All of the content of the CBOR section has saved and migrated to https://msporny.github.io/did-representation-cbor/index.html , which is pending transfer to W3C via @iherman.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/735.html" title="Last updated on May 15, 2021, 4:12 PM UTC (759773a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/735/ab18a18...759773a.html" title="Last updated on May 15, 2021, 4:12 PM UTC (759773a)">Diff</a>

### CODE REVIEW

**Comment by iherman** [comment]
@msporny 

> 
> All of the content of the CBOR section has saved and migrated to https://msporny.github.io/did-representation-cbor/index.html , which is pending transfer to W3C via @iherman.
> 

@msporny, I have created https://github.com/w3c/did-cbor-note right after the working group call (and I believe I notified you about it...), ie, it was unnecessary to do it in a different repo...

Anyway, I have copied index.html and common.js to the official repo, and changed the github repository reference in index.html. For some reason, though, github had problem creating the github page; I am not sure why. It may be a temporary github problem (I can look at it later, but you may be able to bit me into it.)

**Review by iherman — APPROVED** [review]

**Comment by msporny** [comment]
> @msporny, I have created https://github.com/w3c/did-cbor-note right after the working group call (and I believe I notified you about it...), ie, it was unnecessary to do it in a different repo...

Ah, I didn't know.

I've tried to splice the correct history together for the new repo, but don't have the rights to force push to the main branch to clean up the history... can you please give me access to force push to the main branch?

If not, please make https://github.com/w3c/did-cbor-note/tree/main-spliced-history the main branch.

**Comment by iherman** [comment]
@msporny, I hope I found the right settings in the cbor repository...

**Comment by msporny** [comment]
> @msporny, I hope I found the right settings in the cbor repository...

Hooray, you did. I was able to force-push main... history is correct now, feel free to put branch protection back on main now.

The spec is now available here:

https://w3c.github.io/did-cbor-note/

**Comment by iherman** [comment]
> Hooray, you did. I was able to force-push main... history is correct now, feel free to put branch protection back on main now.

That is part of the branch protection part; I will just leave it as is.

**Review by peacekeeper — APPROVED** [review]

**Review by brentzundel — APPROVED** [review]

**Comment by msporny** [comment]
Substantive (but covered by an at risk marker noting potential removal), multiple positive reviews, no objections, merging.

**Pull request merged**
