### PR TITLE
Change note on order to advisement

### PR DESCRIPTION
**Pull request by OR13**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/665.html" title="Last updated on Feb 19, 2021, 1:30 AM UTC (27b5fe4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/665/e5903fa...27b5fe4.html" title="Last updated on Feb 19, 2021, 1:30 AM UTC (27b5fe4)">Diff</a>

### CODE REVIEW

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
@TallTed, now's your time to try a few things out with this advisement.

**Review by brentzundel — APPROVED** [review]
adding @TallTed 's text from https://github.com/w3c/did-core/issues/656#issuecomment-780827629 would be good

**Review by rhiaro — APPROVED** [review]

**Comment by TallTed** [comment]
Repeating [my comment from over there](https://github.com/w3c/did-core/issues/656#issuecomment-780827629), over here --

I want to make a small change to the text within that box ... but it's further away from the single-word change you made than github will allow me to make a suggestion on.

I'd change --
```pre
    <p class="note" title="Ordering of values">
As a result of the <a href="#data-model">data model</a> being defined using
terminology from [[INFRA]], property values which can contain more than one
item, such as <a data-cite="INFRA#ordered-map">maps</a> and
<a data-cite="INFRA#ordered-set">sets</a>, are explicitly ordered. For the
purposes of this specification, unless otherwise stated, ordering is not
important and implementations are not expected to produce or consume
deterministically ordered values.
    </p>
```
-- to --
```pre
    <p class="advisement" title="Ordering of values">
As a result of the <a href="#data-model">data model</a> being defined using
terminology from [[INFRA]], property values which can contain more than one
item, such as <a data-cite="INFRA#ordered-map">maps</a> and
<a data-cite="INFRA#ordered-set">sets</a>, are explicitly ordered. (All
list-like value structures in [[INFRA]] are ordered, whether or not that 
order is significant.) For the
purposes of this specification, unless otherwise stated, ordering is not
important and implementations are not expected to produce or consume
deterministically ordered values.
    </p>
```
To be clear, I've added `(All list-like value structures in [[INFRA]] are ordered, whether or not that order is significant.)`

And I still think that all the links to "INFRA#ordered-set" within the document should be changed to an internal description that includes something like "The order of values in this list-like structure isn't significant, even though INFRA says it is" before the reader gets to the INFRA site.

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
Applied @TallTed's changes in 27b5fe4d235ff5af89e606bb809c1a148bbe3266.

**Comment by msporny** [comment]
Editorial, multiple reviews, changes requested and made, no objections, merging.

**Pull request merged**
