### PR TITLE
add editorial clarification for controller and VM semantics

### LINKED ISSUE #806: Properly define the semantics of all `controller` properties
The semantics of the term 'DID controller' seems clear enough from the [spec](https://www.w3.org/TR/did-core/#did-controller). However, the semantics of the `controller` property in a [verification method](https://www.w3.org/TR/did-core/#verification-methods) is not defined. Some might imagine what it could be from reading the note that discusses Verification method controller(s) and DID controller(s), but it isn't clear. In particular, readers that aren't deeply involved in the subject matter will lack the criteria to determine which of suggested meanings would be the intended one.

The note suggests to me a number of possible meanings. Using the terms
- 'controller' for a [party](https://trustoverip.github.io/essiflab/glossary#party) that is referred to by (a DID in) a 'controller property' in a verification method section, and 
- 'DID controller' for a [party](https://trustoverip.github.io/essiflab/glossary#party) that is referred to by (a DID in) a controller property of the DID document itself;

I then find the following two (contradictory) statements plausible interpretations of the text in the aforementioned note:
- Since a DID controller can change the entire DID document, and the semantics of the controller property are the same when the subject of the relationship is the DID document as when the subject of the relationship is a verification method, it follows that any controller can also change the DID document.
- Since 'controlling something' seems to mean 'the ability to change that something', a controller seems to able to change the verification method in which it is mentioned.

### PR DESCRIPTION
**Pull request by kdenhartog**
Closes #806

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/809.html" title="Last updated on Dec 13, 2021, 11:06 PM UTC (ab7ef21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/809/d20b7c7...ab7ef21.html" title="Last updated on Dec 13, 2021, 11:06 PM UTC (ab7ef21)">Diff</a>

### CODE REVIEW

**Comment by kdenhartog** [comment]
Looks like the IPR bot may be failing for all new PRs here

**Comment by brentzundel** [comment]
> Looks like the IPR bot may be failing for all new PRs here

@iherman could you look into this?

**Comment by iherman** [comment]
> > Looks like the IPR bot may be failing for all new PRs here
> 
> @iherman could you look into this?

I have sent  a note to our system wizards.

**Comment by iherman** [comment]
> > > Looks like the IPR bot may be failing for all new PRs here
> > 
> > 
> > @iherman could you look into this?
> 
> I have sent a note to our system wizards.

... who were very quick in settling it! 😀

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
Class 2, editorial, reviewed, no changes requested, no objections, merging.

**Pull request merged**
