### PR TITLE
Updated the data model diagram

### PR DESCRIPTION
**Pull request by iherman**
As referred to in https://github.com/w3c/did-core/pull/596#issuecomment-783989033 and in https://github.com/w3c/did-core/pull/597#issuecomment-783991200, updating figure 3 (the diagram in the Data Model) to separate core properties and representation specific entries.

Because preview cannot present referenced images, here is the content of the file in PNG (the one in the spec is SVG):

diagram-did-document-entries

I was not sure of all the labels; they are a mouthful on the diagram... But maybe it is o.k.

### CODE REVIEW

**Comment by TallTed** [comment]
The red label (and to a lesser extent, the red box) feels like a warning. Could that maybe be a deep green?

**Comment by iherman** [comment]
> The red label (and to a lesser extent, the red box) feels like a warning. Could that maybe be a deep green?

I am fine with this, I think it is a good idea.

(Collecting comments before effectively doing this, though)

**Comment by peacekeeper** [comment]
Happy for @iherman to "own" this diagram going forward. For reference, here is the source file of my original version:

[data-model-diagram.zip](https://github.com/w3c/did-core/files/6028941/data-model-diagram.zip)

I'm planning to work on updating https://github.com/w3c/did-core/pull/596 and https://github.com/w3c/did-core/pull/597.

**Review by OR13 — APPROVED** [review]

**Comment by peacekeeper** [comment]
Suggestions:

- Rename "Standard Representation-specific entries" to "Core representation-specific entries"
- Rename "Extra Representation-specific Entries" to "Representation-specific entry extensions" or "Extended representation-specific entries"

Just for consistency...

**Comment by iherman** [comment]
I have just made some adjustments on the diagram, mainly following the comments of @peacekeeper and @TallTed. Here is how the updated figure looks like:

diagram-did-document-entries

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
Editorial, multiple reviews, changes requested and made, no objections, merging.

**Pull request merged**
