### PR TITLE
DID Documents section review

### PR DESCRIPTION
**Pull request by grantnoble**
- Line length changes
- wording and punctuation updates
- changing of ordered lists to unordered lists (the rationale that ordered lists should be used for steps or procedures)
- removal of unnecessary "Example" intros
- Linking of JSON-LD Context references

***
<a href="https://pr-preview.s3.amazonaws.com/grantnoble/did-core/pull/117.html" title="Last updated on Nov 21, 2019, 4:03 AM UTC (75592aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/117/a8d0c28...grantnoble:75592aa.html" title="Last updated on Nov 21, 2019, 4:03 AM UTC (75592aa)">Diff</a>

### CODE REVIEW

**Comment by rhiaro** [comment]
This is gonna conflict with https://github.com/w3c/did-core/pull/108 but we can keep this around and pull in any edits that affect the remaining text if 108 is merged

**Comment by grantnoble** [comment]
Given that the section has changed, would it be easier to just re-review it, instead of trying to merge the conflicts?

**Comment by msporny** [comment]
Merge conflicts.

**Comment by grantnoble** [comment]
The conflicts are too hard to resolve, at least for me, so I'm close this PR and do another review of the section.

**Pull request closed without merging**
