### PR TITLE
Adding '-specific' to 'representation property'

### PR DESCRIPTION
**Pull request by shigeya**
Addresses #500

***
<a href="https://pr-preview.s3.amazonaws.com/shigeya/did-core/pull/501.html" title="Last updated on Dec 14, 2020, 11:05 PM UTC (41e7195)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/501/2eef04c...shigeya:41e7195.html" title="Last updated on Dec 14, 2020, 11:05 PM UTC (41e7195)">Diff</a>

### CODE REVIEW

**Review by peacekeeper — CHANGES_REQUESTED** [review]
Our understanding after the TPAC Virtual F2F meeting was that we would not call them properties at all, but rather "representation-specific syntax". This terminology should be discussed in https://github.com/w3c/did-core/issues/463.

**Comment by msporny** [comment]
Discussion ongoing iN #463.

**Comment by msporny** [comment]
Discussion ongoing in #463.

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
@shigeya, PR #566 looks like it's gaining consensus and would replace this PR.

I'm going to close this PR in favor of PR #566.

**Pull request closed without merging**
