### PR TITLE
Ensure publicKeyMultibase values are valid.

### PR DESCRIPTION
**Pull request by msporny**
This PR fixes the `publicKeyMultibase` values in the specification to ensure that they're correctly encoded.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/807.html" title="Last updated on Dec 8, 2021, 8:51 PM UTC (685b441)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/807/d20b7c7...685b441.html" title="Last updated on Dec 8, 2021, 8:51 PM UTC (685b441)">Diff</a>

### CODE REVIEW

**Review by OR13 — CHANGES_REQUESTED** [review]
I don't think this change is correct, here is an example from our did:key implementation:

[z6MkmM42vxfqZQsv4ehtTjFFxQ4sQKS2w6WR7emozFAn5cxu](https://did.key.transmute.industries/did:key:z6MkmM42vxfqZQsv4ehtTjFFxQ4sQKS2w6WR7emozFAn5cxu)  - works


[zH3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV](https://did.key.transmute.industries/did:key:zH3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV) - does not work

**Comment by msporny** [comment]
> I don't think this change is correct, here is an example from our did:key implementation:
> 
> [z6MkmM42vxfqZQsv4ehtTjFFxQ4sQKS2w6WR7emozFAn5cxu](https://did.key.transmute.industries/did:key:z6MkmM42vxfqZQsv4ehtTjFFxQ4sQKS2w6WR7emozFAn5cxu)

Hrm, clicking the link places a `%60` at the end for me... but if I copy-paste the link from your raw comment, it works for me?

**Comment by msporny** [comment]
> [zH3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV](https://did.key.transmute.industries/did:key:zH3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV) - does not work

Yes, exactly, that's the bug that this PR fixes?

**Comment by selfissued** [comment]
What are the specs that the existing and new values conform to and why the changes?  There's not sufficient background in this PR to understand why these changes are being proposed or to validate that they're correct.

**Comment by msporny** [comment]
> What are the specs that the existing and new values conform to and why the changes? 

The spec is here:

https://w3c-ccg.github.io/did-method-key/

The old values were based on raw base58 values (no multicodec header), IIRC.

> There's not sufficient background in this PR to understand why these changes are being proposed or to validate that they're correct.

The changes are being proposed because the current values are wrong. You can validate that they're correct by checking against multiple implementations that implement the `publicKeyMultibase` values.

**Comment by OR13** [comment]
ahh, i think I must have copy pasted the wrong values lol... yes, this fix should be applied.

**Review by OR13 — APPROVED** [review]

**Review by mprorock — APPROVED** [review]

**Review by kdenhartog — APPROVED** [review]

**Review by dlongley — APPROVED** [review]

**Review by gannan08 — APPROVED** [review]
LGTM

**Review by clehner — APPROVED** [review]

**Review by peacekeeper — APPROVED** [review]
We recently came across this in some EBSI-related work, and had a discussion in DIF yesterday.

Also see https://w3c-ccg.github.io/lds-ed25519-2020/#ed25519verificationkey2020, which says that the publicKeyMultibase value contains multibase+multicodec.

Therefore this fix is correct.

**Comment by msporny** [comment]
Class 2, editorial, multiple reviews, no changes requested, no remaining objections, merging.

**Pull request merged**
