### PR TITLE
Change "herd immunity" to "herd privacy"

### PR DESCRIPTION
**Pull request by peacekeeper**
@dhh1128 I assume this is what you meant in https://github.com/w3c/did-core/pull/515?

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/541.html" title="Last updated on Jan 18, 2021, 9:54 AM UTC (35f3b53)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/541/af9c06b...35f3b53.html" title="Last updated on Jan 18, 2021, 9:54 AM UTC (35f3b53)">Diff</a>

### CODE REVIEW

**Review by dhh1128 — APPROVED** [review]
I am chuckling. The pandemic has affected us in more ways than we realize. :-)

**Comment by peacekeeper** [comment]
Fixes #538.

**Review by brentzundel — APPROVED** [review]

**Review by TallTed — APPROVED** [review]

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
Merge conflicts. Please fix, @peacekeeper.

**Comment by peacekeeper** [comment]
Resolved merge conflicts.

**Comment by msporny** [comment]
Editorial, multiple positive reviews, no objections, merging.

**Pull request merged**
