### PR TITLE
Update main from master

### PR DESCRIPTION
**Pull request by brentzundel**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/482.html" title="Last updated on Dec 10, 2020, 5:26 PM UTC (b08d7ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/482/e715ba4...b08d7ec.html" title="Last updated on Dec 10, 2020, 5:26 PM UTC (b08d7ec)">Diff</a>

### CODE REVIEW

**Comment by iherman** [comment]
@brentzundel @msporny I am not sure what this PR is all about. Are the 'main' and 'master' branches in sync, so that I can flip the default branch name?

**Comment by brentzundel** [comment]
> @brentzundel @msporny I am not sure what this PR is all about. Are the 'main' and 'master' branches in sync, so that I can flip the default branch name?

From what I can tell, `main` and `master` are out of sync. This PR brings them into sync again.

**Comment by msporny** [comment]
> From what I can tell, main and master are out of sync. This PR brings them into sync again.

No need to do this, we're going to immediately delete the `master` branch once we switch to `main`. Closing.

**Comment by brentzundel** [comment]
> > From what I can tell, main and master are out of sync. This PR brings them into sync again.
> 
> No need to do this, we're going to immediately delete the `master` branch once we switch to `main`. Closing.
> 
> @iherman, just flip the switch now and make `main` the default branch. I will delete `master` immediately after doing that.

`master` branch has commits and changes that `main` doesn't. Shouldn't those changes be brought from `master` to `main` before we remove `master`? What am I missing?

**Comment by msporny** [comment]
> `master` branch has commits and changes that `main` doesn't. Shouldn't those changes be brought from `master` to `main` before we remove `master`? What am I missing?

Ah, you /were/ correct -- main was missing @csuwildcat's fixes because I targeted the wrong branch. That has been fixed. Now main should be up to date (modulo pending PRs):

https://github.com/w3c/did-core/branches

The reason `master` is behind now is because of the major surgery that had to be done to get @csuwildcat's changes in (multiple cross merges, out of date repo from Aug 5th, etc.)... and because @brentzundel pushed a merge to master (please don't ever merge to master... just do squash or rebase to keep history in a single stream and easy to follow for IPR purposes).

Soooo, /now/ everything should be good to go, but please check again @brentzundel so I'm not missing something. Good catch, should be fixed now.

**Comment by iherman** [comment]
Ok, it is evening here, ie, I have called it a day. I can flip the branches tomorrow morning, provided there is a clear nod from both of you to do it!

**Comment by msporny** [comment]
*\*clear nod to flip the branches\** :)

**Pull request closed without merging**
