### PR TITLE
Remove proof as it is specific to Linked Data Proofs. Fixes #293

### LINKED ISSUE #293: Remove `proof`
`proof` should not be in DID Core as it is a way to protect content not used by all DID methods. Propose removing it altogether, understanding that it will still be available for those that want to use it via the DID Spec Registries.

### PR DESCRIPTION
**Pull request by rhiaro**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/305.html" title="Last updated on May 31, 2020, 2:57 PM UTC (d846737)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/305/490cccb...d846737.html" title="Last updated on May 31, 2020, 2:57 PM UTC (d846737)">Diff</a>

### CODE REVIEW

**Comment by rhiaro** [comment]
If there are objections to removing `proof` altogether, suggest we mark it as at-risk.

**Comment by peacekeeper** [comment]
I approve this if @dmitrizagidulin approves it too :)

**Comment by msporny** [comment]
The reasoning for removing `proof` is not that it's not useful. The use of `proof` to protect the contents of the DID Document is very useful... but it's a part of the Linked Data Security stack. This property comes from a time when we expected DID Documents to be signed on all ledgers, but that's not how things have played out. All that said, it's still possible that DID Documents /can/ be signed on ledger using the Linked Data Security stack... but the DID Core spec should be silent on how DID Documents are protected on-ledger. That is a DID Method implementation specific detail. Therefore, we should remove `proof` from the core spec and let it live in the Linked Data Security specs.

**Comment by msporny** [comment]
Normative, multiple positive reviews, no objections, merging.

**Pull request merged**
