### PR TITLE
Removed JSON-LD explainer.

### LINKED ISSUE #206: JSON LD Explanatory Text is extraneous
The JSON LD explanation and justification text currently in the serialization section does not belong in this specification. Those using JSONLD will already know what it is and don't need to have it explained. Those not using JSONLD don't care. It should be removed from the document, and certainly doesn't belong in a section on how to represent content on the wire. It's our responsibility to tell people how to take a DID document to and from a given representation, not extol the virtues of any representation above another.

### PR DESCRIPTION
**Pull request by jricher**
Closes #206

***
<a href="https://pr-preview.s3.amazonaws.com/jricher/did-core/pull/239.html" title="Last updated on Mar 24, 2020, 4:22 PM UTC (451c9d4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/239/fd4c5cf...jricher:451c9d4.html" title="Last updated on Mar 24, 2020, 4:22 PM UTC (451c9d4)">Diff</a>

### CODE REVIEW

**Comment by iherman** [comment]
@jricher you should connect your github account with the W3C one at https://www.w3.org/users/112833

**Comment by jricher** [comment]
@iherman I have done that several times, I'm not sure what I'm doing wrong 🤷‍♀️

**Comment by kdenhartog** [comment]
> 
> 
> @iherman I have done that several times, I'm not sure what I'm doing wrong 🤷‍♀️

Could it be because his github handle is missing [here](https://github.com/w3c/did-wg/blob/710545348269e6db428095a01d8c6180952bd9f1/assets/nicknames.json#L385)?

**Comment by iherman** [comment]
> > @iherman I have done that several times, I'm not sure what I'm doing wrong 🤷‍♀️
>
> Could it be because his github handle is missing here?

@kdenhartog no, that is not it. That file is more-or-less a private data file that I maintain, which helps to do manipulation on github without a need to ask people to give me their github id again and again. (Which reminds me that I have to add Justin's id there:-)

**Comment by iherman** [comment]
> @iherman I have done that several times, I'm not sure what I'm doing wrong 🤷‍♀️

@jricher I really do not know. Try to add it there again and then ping me (e.g., on IRC or email), I will check whether it went through and, if not, I will contact our system people...

**Comment by msporny** [comment]
We agreed at the DID WG F2F meeting in Amsterdam to move this text to the implementation guidance. I've done that in this commit:

https://github.com/w3c/did-imp-guide/commit/304c6194f25acb0cb6208b526828ad62560030ea

I'll note that the DID Implementer Guide still has no Editors, probably something that needs to be addressed sooner than later.

In the meantime, the commit above clears the way to get this PR merged.

**Pull request merged**
