### PR TITLE
Editorial updates from Ivan, #2

### PR DESCRIPTION
**Pull request by rhiaro**
I ran through #403 and this PR contains the suggested changes that are editorial and uncontroversial; see individual commits for details.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/441.html" title="Last updated on Nov 2, 2020, 8:51 AM UTC (2593704)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/441/58225f1...2593704.html" title="Last updated on Nov 2, 2020, 8:51 AM UTC (2593704)">Diff</a>

### CODE REVIEW

**Review by iherman — APPROVED** [review]
I have put check marks in #403 that, I believe, are covered by this PR. @rhiaro you should also check this, please.

**Review by brentzundel — APPROVED** [review]

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
Please fix merge conflicts, good to go after that.

**Comment by rhiaro** [comment]
Rebased and fixed conflicts

**Comment by msporny** [comment]
Editorial, multiple positive reviews, no objections, merging.

**Pull request merged**
