### PR TITLE
Attempt to fix ABNF for  id-char and param-char

### PR DESCRIPTION
**Pull request by OR13**
Attempts to address: https://github.com/w3c/did-core/issues/45

Not super confident I captured this correctly.

***

### :boom: Error: 504 Gateway Time-out :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 15, 2020, 7:34 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2FOR13%2Fdid-core%2Fdd98b52ef3db53fc7bbe4ba935f0b8d149e3eda7%2Findex.html%3FisPreview%3Dtrue)

```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/did-core%23222.)._
</details>

### CODE REVIEW

**Comment by davidlehn** [comment]
This is going against #215 and #216 and allowing unrestricted colon use.

**Comment by OR13** [comment]
@davidlehn 

Should it be: `*( ":" *id-char ) 1*id-char` instead? 

I'm very unfamiliar with ABNF, I just tried to close all issues that where "ready for pr"...

**Comment by davidlehn** [comment]
I'm not really sure what problem is being addressed.

Reverting the method-specific-id rule but leaving idchar/id-char with colon would just verbosely allow unrestricted colons so that doesn't make sense.

**Comment by OR13** [comment]
@davidlehn https://github.com/w3c/did-core/issues/45

names should be snake-case, can you make a suggestion that would solve this?

**Comment by davidlehn** [comment]
If it's just about changing `idchar` to `id-char`, that's fine.  But this PR also added `":"` to `id-char`.  I can't tell if #45 is about more than just that minor update.

**Comment by OR13** [comment]
@msporny I added the "pending-close" label based on @peacekeeper 's feedback... can we do the same for the linked issue? I'm not an editor on this spec... so I am not gonna add a label to things I'm not in control of... (like the linked issue).

**Comment by OR13** [comment]
I'm just gonna close this.

**Pull request closed without merging**
