### PR TITLE
Remove "unauthorized" and add "deactivated" error code.

### PR DESCRIPTION
**Pull request by peacekeeper**
Addresses https://github.com/w3c/did-core/issues/402.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/440.html" title="Last updated on Oct 29, 2020, 10:02 PM UTC (ddd8bb5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/440/5dd10b5...ddd8bb5.html" title="Last updated on Oct 29, 2020, 10:02 PM UTC (ddd8bb5)">Diff</a>

### CODE REVIEW

**Comment by peacekeeper** [comment]
The question of resolution/dereferencing error codes started earlier this year when we added the DID Resolution section. Based on the discussions back then, and the comments in issue https://github.com/w3c/did-core/issues/402, the idea is that we include a minimal set of error codes in DID Core, and allow additional codes to be assigned via the DID Spec Registries in the future.

With this PR, we would have:

- For DID resolution: `invalid-did`, `not-found`, `deactivated`
- For DID URL dereferencing: `invalid-did-url`, `not-found`, `deactivated`

**Review by kdenhartog — COMMENTED** [review]
I like adding the deactivated error, and I think it would remain beneficial to keep unauthorized as well. In the case of resolving dids from a public resolver connected to a private VDR (such as an intranet web server with did:web or a private hyperledger fabric network) I think it's beneficial to indicate the DID exists, but the resolver cannot return the DID Document without some form of authorization provided in the request. This bodes well for a zero trust architecture where the resolver service is acting as an authorization point for a resource (the DID Document).

With that in mind, this does open the question do we need to be able to provide authorization proof in the resolution options parameter?

**Comment by peacekeeper** [comment]
I feel pretty strongly that in the DID Core spec we should not talk about authorization of DID resolution and therefore remove the error code. This doesn't mean that such an error code and also some kind of authorization input metadata is not possible or not allowed, those things can be done and even added later to the DID Spec Registries. But if we want to address this now in DID Core, it would be a major new feature that we don't have time to discuss. As far as I remember, by default, we have always considered DID resolution to not require authorization.

If we want to specify this at some point, we could define the required metadata and error codes elsewhere, e.g. in DID Resolution, and then register those extensions in the DID Spec Registries.

**Comment by agropper** [comment]
+1 Markus. I think this is a complicated issue in terms of privacy. Happy
to engage if the group thinks it’s important but we would need to develop
some use cases to discuss further.

**Review by msporny — APPROVED** [review]

**Review by OR13 — APPROVED** [review]

**Review by brentzundel — APPROVED** [review]

**Comment by peacekeeper** [comment]
Merge conflicts should be resolved now.

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
Normative, multiple positive reviews, no objections, merging.

**Pull request merged**
