### PR TITLE
Use `publicKeyMultibase` instead of `publicKeyBase58` field in all examples

### PR DESCRIPTION
**Pull request by Patrik-Stas**
Hi, I believe that some examples were by mistake using `publicKeyBase58` rather than `publicKeyMultibase` - I've updated the examples. Let me know if I am missing something.

Cheers

***
<a href="https://pr-preview.s3.amazonaws.com/Patrik-Stas/did-core/pull/852.html" title="Last updated on Jul 7, 2024, 7:58 PM UTC (7edae25)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/852/a8ddc80...Patrik-Stas:7edae25.html" title="Last updated on Jul 7, 2024, 7:58 PM UTC (7edae25)">Diff</a>

### CODE REVIEW

**Comment by msporny** [comment]
The examples use `Ed25519VerificationKey2018`, which only supported `publicKeyBase58`. We do plan to update the examples to use more modern key formats such as `Multikey`, which does use `publicKeyMultibase`.

**Comment by msporny** [comment]
@Patrik-Stas could you please update the PR to use `Multikey`, you can find the format description here:

https://w3c.github.io/controller-document/#multikey

**Comment by decentralgabe** [comment]
Related to the context discussion on today's call. Suggestion is to pull in the new multikey context.

**Comment by pchampin** [comment]
This was discussed during the WG meeting on 2024-08-22:
https://www.w3.org/2024/08/22-did-minutes.html#t06

**Comment by msporny** [comment]
Since we haven't heard back from the original author yet, I'll effect these changes on the core specification.

**Comment by pchampin** [comment]
This was discussed during the [#did meeting on 19 September 2024](https://www.w3.org/2024/09/19-did-minutes.html#t05).

<details><summary><i>View the transcript</i></summary>

<h4><a href="https://github.com/w3c/did-core/pull/852" rel="noopener noreferrer">w3c/<wbr>did-core#852</a></h4>
<p><cite>manu:</cite> This one is waiting on merge conflict resolution<br>
<span>… We might have to do a more complete fix with this one. Or pull the PR in and make the fix later</span></p>
<p><cite>decentralgabe:</cite> I noticed you tagged the author. If manu you can take it over that would be great</p>
<p><cite>manu:</cite> Sure, I can take it over.</p>
<p><cite>ivan:</cite> Why do you think it is aclass 2 change? I think it is a class 3<br>
<span>… using public key multibase effects implementations</span></p>
<p><cite>manu:</cite> It effects the examples, this is non-normative</p>
<p><cite>ivan:</cite> Okay, yep its a class 2</p>
<p><cite>manu:</cite> There is a separate issue that discusses upgrading to publicKeyMultibase</p>
<p><a href="https://github.com/w3c/did-core/issues" rel="noopener noreferrer">https://<wbr>github.com/<wbr>w3c/<wbr>did-core/<wbr>issues</a></p>

<hr /></details>

**Comment by msporny** [comment]
This PR has been merged into PR #867. Closing.

**Pull request closed without merging**
