### PR TITLE
abstract: update for accuracy

### PR DESCRIPTION
**Pull request by rhiaro**
Small change to abstract to make it more accurate

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/576.html" title="Last updated on Jan 31, 2021, 10:54 PM UTC (5baac48)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/576/db9c492...5baac48.html" title="Last updated on Jan 31, 2021, 10:54 PM UTC (5baac48)">Diff</a>

### CODE REVIEW

**Review by TallTed — APPROVED** [review]

**Review by talltree — APPROVED** [review]
Good catch, Amy.

**Review by brentzundel — APPROVED** [review]

**Review by msporny — APPROVED** [review]
A bit concerned that the topic is too advanced for the abstract and will confuse people. This is accurate, though, we may want to remove this down further at a future point in time.

**Comment by msporny** [comment]
@rhiaro merge conflicts, please fix.

**Comment by msporny** [comment]
Editorial, multiple reviews, concerns raised, no objections, merging.

**Pull request merged**
