### PR TITLE
(editorial) restore apparently accidental deletion

### PR DESCRIPTION
**Pull request by TallTed**
happened in #616

***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-core/pull/658.html" title="Last updated on Feb 16, 2021, 4:08 PM UTC (e245c1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/658/9f78b2c...TallTed:e245c1d.html" title="Last updated on Feb 16, 2021, 4:08 PM UTC (e245c1d)">Diff</a>

### CODE REVIEW

**Comment by peacekeeper** [comment]
I agree it looks like this line was probably deleted by accident. @jandrieu can you confirm?

**Comment by brentzundel** [comment]
Looks like I never got around to finishing my review of #616: 
image

I agree this probably shouldn't have been deleted.

**Review by rhiaro — APPROVED** [review]

**Review by jandrieu — APPROVED** [review]
Good catch.

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
Oops. Thanks!

**Comment by msporny** [comment]
Editorial, multiple positive reviews, no objections, merging.

**Pull request merged**
