### PR TITLE
Disallow empty method-specific-id in ABNF.

### PR DESCRIPTION
**Pull request by peacekeeper**
Addresses #34

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/216.html" title="Last updated on Mar 5, 2020, 1:00 PM UTC (e26affd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/216/ad87e73...e26affd.html" title="Last updated on Mar 5, 2020, 1:00 PM UTC (e26affd)">Diff</a>

### CODE REVIEW

**Comment by peacekeeper** [comment]
This changes the `method-specific-id` ABNF rule to allow leading and consecutive colons, but disallows a trailing colon or an empty `method-specific-id`.

E.g. allowed:

```
did:ex:123
did:ex::123
did:ex:sub:123
did:ex:sub::more:123
did:ex:sub::more::123
```

E.g. disallowed:

```
did:ex
did:ex:
did:ex:sub:
```

**Comment by davidlehn** [comment]
https://github.com/w3c/did-core/pull/215 proposes text saying use of colons is "entirely method specific".  That seems to be a slight conflict with also restricting their trailing use here.

**Comment by peacekeeper** [comment]
>  That seems to be a slight conflict with also restricting their trailing use here.

Thanks @davidlehn for pointing this out, I just updated https://github.com/w3c/did-core/pull/215 to reflect this. Do you agree with this change?

**Comment by davidlehn** [comment]
@peacekeeper Sure.  I added related comments to the other PR.

**Pull request merged**
