### PR TITLE
At Risk statement for ABNF not allowing an empty method-id-string

### PR DESCRIPTION
**Pull request by talltree**
This PR simply notes that some DID methods have expressed an interest in the possibility of resolving an DID method name by itself to discover metadata describing how to connect to the associated verifiable data registry. So there is a chance this one ABNF rule could change in the CR.

***
<a href="https://pr-preview.s3.amazonaws.com/talltree/did-core/pull/477.html" title="Last updated on Dec 11, 2020, 12:16 AM UTC (e02022c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/477/e715ba4...talltree:e02022c.html" title="Last updated on Dec 11, 2020, 12:16 AM UTC (e02022c)">Diff</a>

### CODE REVIEW

**Comment by jandrieu** [comment]
@TallTree this looks like a new feature. Is there an issue or other mention before the feature freeze?

**Comment by peacekeeper** [comment]
For reference, this has been previously discussed in https://github.com/w3c/did-core/issues/34, and in https://github.com/w3c/did-core/pull/216 the change was made to disallow an empty `method-specific-id`.

**Comment by talltree** [comment]
> @talltree this looks like a new feature. Is there an issue or other mention before the feature freeze?

Just for clarification, I did not realize that this PR included text from another PR that should not have been in it. I am cleaning that up ASAP. Also, as Markus mentioned, it is not a few feature, see #34 .

**Comment by talltree** [comment]
Replaced by #484

**Pull request closed without merging**
