### PR TITLE
Simplifies spec by using pure JSON instead of JSON-LD

### PR DESCRIPTION
**Pull request by mikelodder7**
***
<a href="https://pr-preview.s3.amazonaws.com/mikelodder7/did-core/pull/146.html" title="Last updated on Dec 20, 2019, 5:21 PM UTC (dd1a82d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/146/26f4891...mikelodder7:dd1a82d.html" title="Last updated on Dec 20, 2019, 5:21 PM UTC (dd1a82d)">Diff</a>

### CODE REVIEW

**Comment by iherman** [comment]
@mikelodder7 , could you associate your github id with your W3C account using https://www.w3.org/users//101578/connectedaccounts ? Thanks.

**Comment by mikelodder7** [comment]
> @mikelodder7 , could you associate your github id with your W3C account using https://www.w3.org/users//101578/connectedaccounts ? Thanks.

It shows in W3C that my github is connected. Is there something else I need to do?

**Comment by TallTed** [comment]
Rather than simply deleting all the JSON-LD content with this PR, perhaps you could move it to the end as a placeholder Appendix (which would be polished/refined/rewritten later), as your text says will be present?

**Comment by iherman** [comment]
> It shows in W3C that my github is connected. Is there something else I need to do?

Nop... I have re-initialized the check and it is now happy:-)

**Comment by talltree** [comment]
> Rather than simply deleting all the JSON-LD content with this PR, perhaps you could move it to the end as a placeholder Appendix (which would be polished/refined/rewritten later), as your text says will be present?

@TallTed I think that's a very constructive suggestion. I believe @mikelodder7 's intention was first to just show what would change in the base spec with a "plain JSON" baseline. Composing the Appendix that would have the full JSON-LD extension is obviously a fair amount of editorial work, however I agree that it would reuse most if not all of what has already been written in the spec in the sections that do explain JSON-LD. So this PR could be revised to just move those sections to an Appendix in order to lay the foundation for that next editorial step.

**Comment by msporny** [comment]
The recent DID WG F2F meeting in Amsterdam resulted in consensus in how to address the issue that this PR is attempting to address. The result of that discussion is here:

https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-01-30-did#section2-5

The editors are currently working on a set of PRs that will implement the consensus position of the group from that meeting. That consensus-based PR will supersede this PR. 

Closing this PR as it goes in a direction that doesn't implement the current consensus position of the group. Feel free to re-open the issue or object and we can bring it up for discussion during the next meeting.

**Pull request closed without merging**
