### PR TITLE
Replacing Figure 1 with a new 'Brief Architecture Overview' diagram

### PR DESCRIPTION
**Pull request by shigeya**
Related to Issue #453.

This is a simplified version of the figure in PR #600.
Now replace it with current Figure 1.

***
<a href="https://pr-preview.s3.amazonaws.com/shigeya/did-core/pull/612.html" title="Last updated on Feb 10, 2021, 1:57 AM UTC (d1a8a84)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/did-core/612/59687a4...shigeya:d1a8a84.html" title="Last updated on Feb 10, 2021, 1:57 AM UTC (d1a8a84)">Diff</a>

### CODE REVIEW

**Comment by shigeya** [comment]
This is the new brief diagram image for your convinience:

did_brief_architecture_overview

**Review by msporny — APPROVED** [review]
Wonderful -- much simpler and approachable, thank you @shigeya!

**Review by brentzundel — APPROVED** [review]

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-02-11-did-topic#section3) on 2021-02-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 3. Questions on Shigeya's diagrams 

_See github pull request [#612](https://github.com/w3c/did-core/pull/612)._




**Manu Sporny:** shigeya, thank you for putting those diagrams together, very helpful for the architecture  

> *Brent Zundel:* +1 big thanks to Shigeya for his PRs

**Manu Sporny:** one concern is that it's a black and white diagram, colour coding may help  
… the simplified diagram still has a number of arrows that look scary  
… I know the point was providing relationships between everything  
… can you provide the source other than svg? google doc? that would allow the editors to iterate?  

**Shigeya Suzuki:** sure  
… it's in my branch of my repo  
… already available  
… if you want them in main, I can commit, or mail it to you  

**Manu Sporny:** ideally the sources are in the repo.. what tool are you using?  

**Shigeya Suzuki:** using OmniGraph on Mac  
… it can export several formats, I will inform you which format is available  

**Manu Sporny:** if it can get into google draw, that seems to be a useful thing  
… if not we can recreate it  
… we just want to get it into a format we can iterate on  
… The other question was layout with the diagram, I'm sure you've tried to lay it out in a way that's easier  
… I'm wondering if we can simplify further and reduce arrows to the minimum  
… it could be that DID URL and DID URL dereferencing could be a different diagram, down in the URL dereferencing section  
… that may simplify the diagram further  
… ideally I think we want 5 concepts in the diagram. 6 to 7 is a bit much  
… at this point we have 15 including the arrows  
… I really appreciate all the work in the diagram  
… trying to see how aggressively simplified we can get  

> *Brent Zundel:* +1 to the idea of separate similar diagrams for each concept

**Manu Sporny:** so people look at the diagram and see it as simple on the surface  

**Brent Zundel:** any other feedback on this?  

**Shigeya Suzuki:** manu says you were going to edit the drawing for colours  
… if there's any colour scheme you want I can add before I provide you?  

**Manu Sporny:** I don't have any suggestions.. whatever looks pretty  

**Shigeya Suzuki:** sure. I suggest some warmer colour scheme, my preference  

**Manu Sporny:** thank you  

> *Justin Richer:* +1 to black and white

</details>

**Comment by msporny** [comment]
Editorial, multiple reviews, changes requested and made, no objections, merging.

**Pull request merged**
